import easyjupyter

from pathlib import Path
from typing import List, Tuple
import argparse
import torch
from configs import ConfigTemplate
from model.bpe_tokenizer import BPETokenizer
from model.model_text_only import TextOnlyModel
from model.utils.masking import create_causal_doc_mask
from tqdm import tqdm
from utils.misc import print_args

from model.utils.model_io import load_checkpoint
import json

import lm_eval
from lm_eval.api.instance import Instance
from lm_eval.api.model import LM
from lm_eval.tasks import TaskManager


class lm_eval_wrapper(LM):
    """
    Wrapper for `lm-evaluation-harness`, to make it work with my custom model.
    """

    def __init__(self, cfg, model, tokenizer):
        super().__init__()
        self.cfg = cfg
        self.model = model
        self.tokenizer = tokenizer

    def loglikelihood(self, requests: list[Instance]) -> list[tuple[float, bool]]:
        """
        Each request contains Instance.args : Tuple[str, str] containing 1. an input string to the LM and 2. a target string on which the loglikelihood of the LM producing this target, conditioned on the input, will be returned.
        Each request will have, as result, (ll, is_greedy): Tuple[float, int] returned, where ll is a floating point number representing the log probability of generating the target string conditioned on the input, and is_greedy being either the value 0 or 1, with it being 1 if and only if the target string would be generated by greedy sampling from the LM (that is, if the target string is the most likely N-token string to be output by the LM given the input. )
        """
        results = []
        with torch.inference_mode():
            for request in tqdm(requests, desc="Calculating Loglikelihood"):
                context, continuation = request.args

                # Tokenize
                context_ids = self.tokenizer.encode(context).ids
                continuation_ids = self.tokenizer.encode(continuation).ids
                con_len = len(continuation_ids)

                # Truncate to fit model's precomputed RoPE context window
                max_seq_len = self.model.freqs_cis.shape[0]
                allowed_context_len = max_seq_len - con_len
                if allowed_context_len < 1:
                    # If continuation alone is larger than context window, truncate it too
                    continuation_ids = continuation_ids[: max_seq_len - 1]
                    context_ids = [context_ids[-1]]
                    con_len = len(continuation_ids)
                elif len(context_ids) > allowed_context_len:
                    # Truncate context from the left
                    context_ids = context_ids[-allowed_context_len:]

                # Combine them to feed the model
                input_ids = torch.tensor(
                    [context_ids + continuation_ids], device=self.cfg.device
                )
                batch_mask = create_causal_doc_mask(self.cfg, token_ids=input_ids)

                logits, _ = self.model(input_ids, batch_mask)

                # logit[:, i, :] predicts token i+i, so the continuation's predicting
                # logits sit one position before each continuation token
                cont_logits = logits[0, -con_len - 1 : -1, :]
                cont_ids_tensor = torch.tensor(continuation_ids, device=self.cfg.device)

                log_probs = torch.log_softmax(cont_logits, dim=-1)
                token_log_probs = log_probs.gather(
                    1, cont_ids_tensor.unsqueeze(-1)
                ).squeeze(-1)
                total_logprob = token_log_probs.sum().item()

                greedy_tokens = cont_logits.argmax(dim=-1)
                is_greedy = bool((greedy_tokens == cont_ids_tensor).all().item())

                results.append((total_logprob, is_greedy))

        return results

    def loglikelihood_rolling(
        self, requests: list[Instance]
    ) -> list[tuple[float, bool]]:
        raise NotImplementedError(
            "`lm_eval_wrapper.loglikelihood_rolling()` is not implemented yet!"
        )

    def generate_until(self, requests: list[Instance]) -> list[str]:
        """
        Each request contains Instance.args : Tuple[str, dict] containing 1. an input string to the LM and 2. a dictionary of keyword arguments used to control generation parameters.
        Using this input and these generation parameters, text will be sampled from the language model (typically until a maximum output length or specific stopping string sequences--for example, {"until": ["\n\n", "."], "max_gen_toks": 128}).
        The generated output text from the model will then be returned.
        """

        results = []
        with torch.inference_mode():
            for request in tqdm(requests, desc="Generating"):
                # Extract the prompt and generation arguments
                prompt, gen_kwargs = request.args[0], request.args[1]
                max_tokens = gen_kwargs.get("max_gen_toks", 128)
                stop_sequences = gen_kwargs.get("until", [])

                # Tokenize prompt
                input_ids = self.tokenizer.encode(prompt).ids
                prompt_len = len(input_ids)
                max_seq_len = self.model.freqs_cis.shape[0]

                # Truncate the prompt to fit model's precomputed RoPE context window minus 1 token to make space for an answer/response
                if prompt_len >= max_seq_len:
                    input_ids = input_ids[-(max_seq_len - 1) :]
                    prompt_len = len(input_ids)

                # Shrink max_tokens so prompt + generated tokens do no exceed max_seq_len
                if prompt_len + max_tokens > max_seq_len:
                    max_tokens = max_seq_len - prompt_len

                input_tensor = torch.tensor([input_ids], device=self.cfg.device)

                # Process prompt entirely and initial KV cache
                batch_mask = create_causal_doc_mask(
                    cfg=self.cfg, token_ids=input_tensor
                )
                logits, kv_cache = self.model(
                    input_tensor, batch_mask, start_pos=0, kv_cache=None
                )
                next_token_id = logits[0, -1, :].argmax(dim=-1).item()

                generated_tokens = []

                start_pos = input_tensor.shape[1]

                # Increment token by token processing via KV Cache
                for _ in range(max_tokens - 1):
                    if next_token_id == self.cfg.special_tokens["doc_end_token"]["ID"]:
                        # If we hit the `doc_end_token` we can break
                        break

                    generated_tokens.append(next_token_id)

                    # Feed only the single newest token ID
                    next_tensor = torch.tensor(
                        [[next_token_id]], device=self.cfg.device
                    )

                    # Single token attention tracking requires a simple matching 1x1 mask matrix
                    single_mask = torch.ones(
                        (1, 1), device=self.cfg.device, dtype=torch.bool
                    )

                    logits, kv_cache = self.model(
                        next_tensor, single_mask, start_pos=start_pos, kv_cache=kv_cache
                    )
                    start_pos += 1
                    next_token_id = logits[0, -1, :].argmax(dim=-1).item()

                generated_text = self.tokenizer.decode(generated_tokens)

                # Stop at the earliest occurrence of a string from stop_sequences in the generated_text
                stop_indices = [
                    generated_text.index(s)
                    for s in stop_sequences
                    if s in generated_text
                ]
                if stop_indices:
                    generated_text = generated_text[: min(stop_indices)]

                results.append(generated_text)

            return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Llama 3 Pre-Training Evaluation CLI.")
    parser.add_argument(
        "--chpt",
        type=str,
        help="Path to the checkpoint directory that contains the checkpoint.pt file.",
    )
    parser.add_argument(
        "--overfit",
        action="store_true",
    )

    args = parser.parse_args()
    print_args(args)

    chpt_step_dir = Path(args.chpt)

    cfg = ConfigTemplate.load(chpt_step_dir)
    cfg.initialize(is_overfit=True if args.overfit else False)

    t = BPETokenizer(cfg)
    success, tokenizer = t.load_tokenizer()
    if not success:
        raise ValueError("Tokenizer file not found!\n")

    model = TextOnlyModel(cfg).to(cfg.device)
    chpt = load_checkpoint(cfg, model=model, chpt_dir=chpt_step_dir)

    model.eval()

    eval_model = lm_eval_wrapper(cfg, model, tokenizer)

    curr_stage = cfg.text_only.pretrain.curr_stage_name

    if curr_stage == "lc_stage":
        """Benchmarks: Benchmarks: Needle-in-a-Haystack, ZeroSCROLLS, InfiniteBench."""
        tasks_to_run = [
            "niah_single_1",  # Needle-in-a-Haystack

            # NOTE: Unfortunately, the ZeroSCROLLS tasks need scripts that HuggingFace has deprecated, so I wont use those benchmarks, maybe later I'll implement my own.
            # Same for `infinitebench_passkey` 

            # "scrolls_qasper",  # ZeroSCROLLS
            # "scrolls_quality",  # ZeroSCROLLS
            # "infinitebench_passkey",  # InfiniteBench
        ]
    elif curr_stage == "annealing_stage" or curr_stage == "complete":
        """Benchmarks: GSM8k and MATH."""
        tasks_to_run = ["gsm8k", "hendrycks_math"]

    # Override niah_single_1 default context length which is 4,096 to be the size of the model's context window
    task_manager = TaskManager(
        metadata={"max_seq_lengths": [cfg.curr_seq_len], "pretrained": "gpt2"}
    )

    results = lm_eval.simple_evaluate(
        model=eval_model,
        tasks=tasks_to_run,
        limit=cfg.text_only.pretrain.max_lm_eval_ds_samples,  # If max_lm_eval_ds_samples != None -> Retrieve a limited number of samples from the lm-evaluation-harness dataset.
        task_manager=task_manager,
    )

    if results is not None:
        print(lm_eval.utils.make_table(results))

    save_path = chpt_step_dir / "eval_results.json"
    with open(save_path, "w") as f:
        json.dump(results, f, indent=4, default=str)

    print(f"\n\nEvaluation results saved to -> {save_path}")
